version: '2.1'

services:
  frontendcapstone:
    image: frontendcapstone
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 7888:7888
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js