version: '3'

services:
  frontendcapstone:
    image: spaetnow/soundstream-waveform
    build: .
    depends_on:
      - 'database'
    environment:
      NODE_ENV: production
    ports:
      - 80:7888

  database:
    image: mongo:latest